### ISSUE TITLE
Build error: too many arguments in call to termio.NewProgressBar

### ISSUE THREAD

**Issue by W1M0R** [gopasspw/gopass-hibp#13]
I get the following build error on commit https://github.com/gopasspw/gopass-hibp/commit/d37534d1a92b0d7dddcd0e274a366c7e5ddef707:

```
./hibp.go:98:30: too many arguments in call to termio.NewProgressBar
        have (int64, bool)
        want (int64)
```

Related line: https://github.com/gopasspw/gopass-hibp/blob/main/hibp.go#L98

termio.NewProgressBar seems to accept only one argument: https://github.com/gopasspw/gopass/blob/555edfb4d3833731a3f5a4acc1b4617f99f696c6/pkg/termio/progress.go#L40

**Comment by dominikschulz** [comment]
Thanks for reporting this.
