### ISSUE TITLE
Makefile: wrong install declaration

### ISSUE THREAD

**Issue by Zlogene** [gopasspw/gopass-hibp#2]
Hello, while I was packaging hibp for gentoo I came across this target in the Makefile:

`install: all install-completion`

but the `install-completion`  instruction is not declared anywhere else in the file, as a result installation fails.

**Comment by dominikschulz** [comment]
Hmm, that should have been fixed in https://github.com/gopasspw/gopass-hibp/commit/43074770a5caae19c4c7208603c9506342886506

**Comment by Zlogene** [comment]
Hm, indeed, but it is not tagged as a release as far as I see (I am packaging the tag)

**Comment by Zlogene** [comment]
btw. pretty much the same problem is in the git-credentials plugin https://github.com/gopasspw/git-credential-gopass/blob/v1.12.0/Makefile#L73

**Comment by Zlogene** [comment]
and summon provider too, could you please make minorfix releases?:)

**Comment by Zlogene** [comment]
and summon provider too, could you please make minorfix releases?:)

**Comment by dominikschulz** [comment]
This should have been long fixed at head and we did have several releases since then.
