### ISSUE TITLE
Test issue

### ISSUE THREAD

**Issue by Fale** [gopasspw/gopass-hibp#50]
When I try to test (in a very minimal environment) gopass-hibp, it fails due to a missing folder that is required by a gopass test file.

I think the test should either create the files that it needs or handle properly the fact that the files do not exists.

```
+ go-rpm-integration check -i github.com/gopasspw/gopass-hibp -b /builddir/build/BUILD/gopass-hibp-1.15.0/_build/bin -s /builddir/build/BUILD/gopass-hibp-1.15.0/_build -V 1.15.0-1.fc38 -p /builddir/build/BUILDROOT/gopass-hibp-1.15.0-1.fc38.x86_64 -g /usr/share/gocode -r '.*example.*' -d github.com/gopasspw/gopass-hibp/pkg/hibp/api
Testing    in: /builddir/build/BUILD/gopass-hibp-1.15.0/_build/src
         PATH: /builddir/build/BUILD/gopass-hibp-1.15.0/_build/bin:/builddir/.local/bin:/builddir/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin
       GOPATH: /builddir/build/BUILD/gopass-hibp-1.15.0/_build:/usr/share/gocode
  GO111MODULE: off
      command: go test -buildmode pie -compiler gc -ldflags " -X github.com/gopasspw/gopass-hibp/version=1.15.0 -extldflags '-Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -Wl,--build-id=sha1 -specs=/usr/lib/rpm/redhat/redhat-package-notes '"
      testing: github.com/gopasspw/gopass-hibp
github.com/gopasspw/gopass-hibp
FAIL	github.com/gopasspw/gopass-hibp [setup failed]
# github.com/gopasspw/gopass-hibp
/usr/share/gocode/src/github.com/gopasspw/gopass/tests/can/can.go:12:12: pattern gnupg/*: no matching files found
```

Same issue happens with gopass-jsonapi, but not gopass itself

**Comment by dominikschulz** [comment]
I think this must be realated to your limited test environment.
In a normal setting (e.g. our GitHub builders) this seems to work just fine.

This package is using `embed.FS` to embed the test data into the package: https://github.com/gopasspw/gopass/blob/master/tests/can/can.go#L12

I don't know what `go-rpm-integration check` but maybe it's missing the required source files?

**Comment by Fale** [comment]
Which required source files should be present to ensure that it works?

As for `go-rpm-integration` it's a script (https://pagure.io/go-rpm-macros/blob/35bd72648fe6cfa372f886b5692936ffb5b4389a/f/bin/go-rpm-integration) and in this case it should basically run `go test`.

**Comment by dominikschulz** [comment]
Yes, exactly `tests/can/gnupg` needs to be present during build time.

**Comment by Fale** [comment]
I think that is exactly the problem:

```
<mock-chroot> sh-5.2# go-rpm-integration check -i github.com/gopasspw/gopass-jsonapi -b /builddir/build/BUILD/gopass-jsonapi-1.15.0/_build/bin -s /builddir/build/BUILD/gopass-jsonapi-1.15.0/_build -V 1.15.0-1.fc38 -p /builddir/build/BUILDROOT/gopass-jsonapi-1.15.0-1.fc38.x86_64 -g /usr/share/gocode -r '.*example.*'
Testing    in: /builddir/build/BUILD/gopass-jsonapi-1.15.0/_build/src
         PATH: /builddir/build/BUILD/gopass-jsonapi-1.15.0/_build/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin
       GOPATH: /builddir/build/BUILD/gopass-jsonapi-1.15.0/_build:/usr/share/gocode
  GO111MODULE: off
      command: go test  -ldflags "-extldflags ''"
      testing: github.com/gopasspw/gopass-jsonapi
github.com/gopasspw/gopass-jsonapi
# github.com/gopasspw/gopass-jsonapi
/usr/share/gocode/src/github.com/gopasspw/gopass/tests/can/can.go:12:12: pattern gnupg/*: no matching files found
FAIL	github.com/gopasspw/gopass-jsonapi [setup failed]
<mock-chroot> sh-5.2# ls /usr/share/gocode/src/github.com/gopasspw/gopass/tests/can/
can.go  can_test.go
<mock-chroot> sh-5.2# 
```

I then only need to understand why they are not there (and why the process worked with 1.12). I guess that for some reasons I'm not properly packaging those files in the gopass package!

**Comment by Fale** [comment]
I managed to find the issue!

I've now specified those files which are now properly shipped (https://src.fedoraproject.org/rpms/gopass/c/3cb55f7065e1eae1e6e2545d491497fb57e6d14e?branch=rawhide). It seems like there is another test error, but it seems completely unrelated to the stated issue :-)

**Comment by dominikschulz** [comment]
You are very welcome. And thanks a lot for your work on maintaining this package. If there is anything we can do to make this easier, please let us know.
